--입양 시각 구하기(1)

--Oracle
SELECT 
  HOUR, 
  COUNT(HOUR) COUNT
FROM(
  SELECT 
    TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) HOUR
  FROM ANIMAL_OUTS
    )
WHERE HOUR BETWEEN 9 AND 19
GROUP BY HOUR
ORDER BY HOUR;


--MySQL
SELECT 
  HOUR(DATETIME) AS HOUR, 
  COUNT(ANIMAL_ID) as COUNT
from ANIMAL_OUTS
where HOUR(DATETIME) between 9 and 19
group by HOUR
order by HOUR;
