--오프라인/온라인 판매 데이터 통합하기

--Orcle
SELECT TO_CHAR(SALES_DATE, 'YYYY-MM-DD') SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ( (SELECT SALES_DATE
           , PRODUCT_ID
           , USER_ID
           , SALES_AMOUNT
        FROM ONLINE_SALE
       WHERE TO_CHAR(SALES_DATE, 'YYYYMM') = '202203')
     UNION ALL
     (SELECT SALES_DATE
           , PRODUCT_ID
           , NULL AS USER_ID
           , SALES_AMOUNT
        FROM OFFLINE_SALE WHERE TO_CHAR(SALES_DATE, 'YYYYMM') = '202203')
   )
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;

--MySQL
